networks:
  blogappnetwork:

services:
  mssql-container:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 8022:1433
    networks:
      - blogappnetwork

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - 6379:6379
    networks:
      - blogappnetwork
    command: ["redis-server", "--appendonly", "yes"]
 
  blogwebapi:
    container_name: BlogWebAPIContainer
    read_only: true
    tmpfs:
      - /tmp
    image: rohitkumar09/blogapp:blogapi-${VERSION_TAG}
    ports:
      - 8001:80
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - mssql-container
      - redis
    networks:
      - blogappnetwork
   
  blogfrontend:
    container_name: BlogFrontendContainer
    read_only: true
    tmpfs:
      - /tmp
    image: rohitkumar09/blogapp:blogfrontend-${VERSION_TAG}
    environment: 
      - VITE_APP_ENV=${APP_ENV}
    ports:
      - 5173:5173
      - 3000:80
    depends_on:
      - blogwebapi
    networks:
      - blogappnetwork