networks:
  blogappnetwork:

volumes:
  mssql_data:
  redis_data:

services:
  mssql-container:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 8022:1433
    networks:
      - blogappnetwork
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - 6379:6379
    networks:
      - blogappnetwork
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
 
  blogwebapi:
    container_name: BlogWebAPIContainer
    image: rohitkumar09/blogapp:blogapi-v1
    ports:
      - 8001:80
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - mssql-container
      - redis
    networks:
      - blogappnetwork
   
  blogfrontend:
    container_name: BlogFrontendContainer
    image: rohitkumar09/blogapp:blogfrontend-v1
    environment: 
      - VITE_APP_ENV=${APP_ENV}
    ports:
      - 5173:5173
      - 3000:80
    depends_on:
      - blogwebapi
    networks:
      - blogappnetwork