name: Blog App CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BACKEND_IMAGE: rohitkumar09/blogapp:blogapi-v1
  FRONTEND_IMAGE: rohitkumar09/blogapp:blogfrontend-v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
  
     - name: Log in to Docker Hub
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
     - name: Build backend image
       run: docker build -t $BACKEND_IMAGE -f BlogWebAPI/BlogWebAPI/Dockerfile ./BlogWebAPI

     - name: Build frontend image
       run: docker build -t $FRONTEND_IMAGE -f BlogFrontend/Dockerfile .