name: Blog App CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BACKEND_IMAGE: rohitkumar09/blogapp:blogapi
  FRONTEND_IMAGE: rohitkumar09/blogapp:blogfrontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set version tag
       id: vars
       run: |
         SHORT_SHA=${GITHUB_SHA::7}
         DATE=$(date +%Y%m%d)
         echo "VERSION_TAG=${DATE}-${SHORT_SHA}" >> $GITHUB_ENV
  
     - name: Log in to Docker Hub
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
     - name: Build backend image
       run: docker build -t $BACKEND_IMAGE-${{ env.VERSION_TAG }} -f BlogWebAPI/BlogWebAPI/Dockerfile ./BlogWebAPI

     - name: Build frontend image
       run: docker build -t $FRONTEND_IMAGE-${{ env.VERSION_TAG }} -f BlogFrontend/Dockerfile ./BlogFrontend

     - name: Push backend image
       run: docker push $BACKEND_IMAGE-${{ env.VERSION_TAG }}

     - name: Push frontend image
       run: docker push $FRONTEND_IMAGE-${{ env.VERSION_TAG }}