name: Blog App CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BACKEND_IMAGE: rohitkumar09/blogapp:blogapi
  FRONTEND_IMAGE: rohitkumar09/blogapp:blogfrontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Bump version in .env file
       id: versioning
       run: |
        ENV_FILE=.env
        CURRENT_TAG=$(grep VERSION_TAG $ENV_FILE | cut -d '=' -f2)
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_TAG"
        PATCH=$((PATCH + 1))
        NEW_TAG="${MAJOR}.${MINOR}.${PATCH}"
        sed -i "s/^VERSION_TAG=.*/VERSION_TAG=${NEW_TAG}/" $ENV_FILE
        echo "VERSION_TAG=${NEW_TAG}" >> $GITHUB_ENV

     - name: Docker login
       uses: docker/login-action@v3.3.0
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build backend image
       run: docker build -t $BACKEND_IMAGE-${{ env.VERSION_TAG }} -f BlogWebAPI/BlogWebAPI/Dockerfile ./BlogWebAPI

     - name: Build frontend image
       run: docker build -t $FRONTEND_IMAGE-${{ env.VERSION_TAG }} -f BlogFrontend/Dockerfile ./BlogFrontend

     - name: Push backend image
       run: docker push $BACKEND_IMAGE-${{ env.VERSION_TAG }}

     - name: Push frontend image
       run: docker push $FRONTEND_IMAGE-${{ env.VERSION_TAG }}

     - name: Update .env with new tag
       run: | 
           echo "VERSION_TAG=${{ env.VERSION_TAG }}" > .env

     - name: Commit updated docker-compose.yml
       run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git add .
         git commit -m "Update version tag to ${{ env.VERSION_TAG }}"
         git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
